### ISSUE TITLE
`Invalid request length` from iOS and macOS

### ISSUE THREAD

**Issue by ygini** [latchset/kdcproxy#61]
Hello,

I'm trying to use `kdcproxy` installed via `apt` on Ubuntu 22.04.4 LTS to use with macOS and iOS endpoints using what Apple call the [Kerberos SSO Extension](https://developer.apple.com/documentation/devicemanagement/extensiblesinglesignonkerberos/extensiondata)

According to their documentation, KKDCP is supported and I can indeed get both macOS and iOS client trying to talk with kdcproxy, however on the kdcproxy side, it fail with an `Invalid request length` error and 400 code.

Here is a sample content body from an intercepted `POST` request from an iOS client:

```
3081f8a081e00481dd6a81da3081d7a103020105a20302010aa30e300c300aa10402020095a2020400a481ba3081b7a00703050050810000a131302fa003020101a12830261b2430613834336339372d353134312d343336662d626335662d623932363864643537643964a2131b1150523330382e4252415641532e54454348a3263024a003020102a11d301b1b066b72627467741b1150523330382e4252415641532e54454348a511180f32303234303332303036333531355aa611180f32303234303431383230333531355aa706020411cfde1aa80e300c020112020111020110020117a1131b1150523330382e4252415641532e54454348
```

This content however seems correctly decoded by http://ldh.org/asn1.html but I'm not expert in ASN.1.

Is there a config issue on my side? A bug on kdcproxy? Something else?

**Comment by simo5** [comment]
Not enough data to say, kdcproxy has been primarily tested using MIT Kerberos

**Comment by simo5** [comment]
When I try to decode via that website I do not get a properly formatted ASn.1 decode, I get this:
```U.P.SEQUENCE {
   [C.P.0] {
      U.P.OCTETSTRING 6a81da3081d7a103020105a20302010aa30e300c300aa10402020095a2020400a481ba3081b7a00703050050810000a131302fa003020101a12830261b2430613834336339372d353134312d343336662d626335662d623932363864643537643964a2131b1150523330382e4252415641532e54454348a3263024a003020102a11d301b1b066b72627467741b1150523330382e4252415641532e54454348a511180f32303234303332303036333531355aa611180f32303234303431383230333531355aa706020411cfde1aa80e300c020112020111020110020117
   }
   [C.P.1] {
      U.P.GeneralString 'PR308.BRAVAS.TECH'
   }
}
```

But that octet string is actually part of the ASN.1 structure,
removing some of it let you decode some more:
```
[C.P.1] {
   U.P.INTEGER 0x05 (5 decimal)
}
[C.P.2] {
   U.P.INTEGER 0x0a (10 decimal)
}
[C.P.3] {
   U.P.SEQUENCE {
      U.P.SEQUENCE {
         [C.P.1] {
            U.P.INTEGER 0x0095 (149 decimal)
         }
         [C.P.2] {
            U.P.OCTETSTRING 
         }
      }
   }
}
[C.P.4] {
   U.P.SEQUENCE {
      [C.P.0] {
         U.P.BITSTRING         # 0050810000
50810000 : 0 unused bit(s); 
      }
      [C.P.1] {
         U.P.SEQUENCE {
            [C.P.0] {
               U.P.INTEGER 0x01 (1 decimal)
            }
            [C.P.1] {
               U.P.SEQUENCE {
                  U.P.GeneralString '0a843c97-5141-436f-bc5f-b9268dd57d9d'
               }
            }
         }
      }
      [C.P.2] {
         U.P.GeneralString 'PR308.BRAVAS.TECH'
      }
      [C.P.3] {
         U.P.SEQUENCE {
            [C.P.0] {
               U.P.INTEGER 0x02 (2 decimal)
            }
            [C.P.1] {
               U.P.SEQUENCE {
                  U.P.GeneralString 'krbtgt'
                  U.P.GeneralString 'PR308.BRAVAS.TECH'
               }
            }
         }
      }
      [C.P.5] {
      }
      U.P.GeneralizedTime '20240320063515Z'
      [C.P.6] {
         U.P.GeneralizedTime '20240418203515Z'
      }
      [C.P.7] {
         U.P.INTEGER 0x11cfde1a (298835482 decimal)
      }
      [C.P.8] {
         U.P.SEQUENCE {
            U.P.INTEGER 0x12 (18 decimal)
            U.P.INTEGER 0x11 (17 decimal)
            U.P.INTEGER 0x10 (16 decimal)
            U.P.INTEGER 0x17 (23 decimal)
         }
      }
   }
}
```

So it seem there may be some issue in the generated ASn.1 or this web service may not beable to properly deal with BER vs DER encoding ...

**Comment by ygini** [comment]
And from the kdcproxy point of view, does that string is decodable? Any idea why it is not when I test it?

Your decoding of it seems to make sense, decoded strings are coherent.

**Comment by ygini** [comment]
This online decoder seems all OK with the ASN1 message in my request

https://lapo.it/asn1js/#MIH4oIHgBIHdaoHaMIHXoQMCAQWiAwIBCqMOMAwwCqEEAgIAlaICBACkgbowgbegBwMFAFCBAAChMTAvoAMCAQGhKDAmGyQwYTg0M2M5Ny01MTQxLTQzNmYtYmM1Zi1iOTI2OGRkNTdkOWSiExsRUFIzMDguQlJBVkFTLlRFQ0ijJjAkoAMCAQKhHTAbGwZrcmJ0Z3QbEVBSMzA4LkJSQVZBUy5URUNIpREYDzIwMjQwMzIwMDYzNTE1WqYRGA8yMDI0MDQxODIwMzUxNVqnBgIEEc_eGqgOMAwCARICARECARACARehExsRUFIzMDguQlJBVkFTLlRFQ0g

I cannot find the logic related to this check https://github.com/latchset/kdcproxy/blob/f61979eca217e53062a90344d6ab853695318089/kdcproxy/codec.py#L36-L39

Is there any related RFC for that part to confirm the length check logic make sense?

**Comment by simo5** [comment]
This is how basic ASN.1 with DER encoding works, you always have a length attribute at the start of a struct.
With BER you can have undetermined lengths, but I do not think BER is a valid encoding here.
It is possible this is an overly strict check, in theory this may be avoided as the asn.1 parser should be able to deal with validating this on its own, but it is good practice.

The MS-KKDCP document describes the protocol: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-kkdcp/5bcebb8d-b747-4ee5-9453-428aec1c5c38
(and it does specify that DER is to be used)

**Comment by ygini** [comment]
What is curious to me here is the fixed value of 4 here for the length field. Is it per RFC for DER?

Here the ASN.1 decoder seems to consider my sample message to have an initial length field of 3

<img width="393" alt="image" src="https://github.com/latchset/kdcproxy/assets/202334/effd5bec-1025-4914-a70b-e4f80f5b3b59">

**Comment by simo5** [comment]
Well the length you need to look at is the one in the DER payload contained in the OCTET STRING, I wen ahead and decoded that one here:
https://lapo.it/asn1js/#aoHaMIHXoQMCAQWiAwIBCqMOMAwwCqEEAgIAlaICBACkgbowgbegBwMFAFCBAAChMTAvoAMCAQGhKDAmGyQwYTg0M2M5Ny01MTQxLTQzNmYtYmM1Zi1iOTI2OGRkNTdkOWSiExsRUFIzMDguQlJBVkFTLlRFQ0ijJjAkoAMCAQKhHTAbGwZrcmJ0Z3QbEVBSMzA4LkJSQVZBUy5URUNIpREYDzIwMjQwMzIwMDYzNTE1WqYRGA8yMDI0MDQxODIwMzUxNVqnBgIEEc_eGqgOMAwCARICARECARACARc

It does turn out *that* one too is encoded in 3 bytes, so this check is probably incorrect.

@tiran does PyASN1 have an easy function to peek at a ASN.1 struct and fetch just the length of the outer TAG?

If so we can easily fix this bug. Otherwise I need to figure out how to properly parse an DER encoded length field of variable length.

**Comment by tiran** [comment]
I don't know from the top of my head. It's been years since I last developed new code with pyasn1 or touched the code base of kdcproxy.

I remember vaguely that Microsoft did some strange things in the protocol. IIRC the message payload is an OctetString which is composed of an uint32 size indicator in big endian followed by an ASN.1 struct. The `4` is coming from the uint32 size field.

**Comment by simo5** [comment]
@ygini I think your client is at fault.
[Here](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-kkdcp/5778aff5-b182-4b97-a970-29c7f911eef2) is the normative text for the krb-message octet string:
 `kerb-message: A Kerberos message, including the 4 octet length value specified in [[RFC4120]](https://go.microsoft.com/fwlink/?LinkId=90458) section 7.2.2 in network byte order.`

And here is the relevant part of [RFC 4120](https://www.rfc-editor.org/rfc/rfc4120.html#section-7.2.2):
 `Each request (KRB_KDC_REQ) and response (KRB_KDC_REP or KRB_ERROR) sent over the TCP stream is preceded by the length of the request as 4 octets in network byte order`

I think you'll have to open a bug against your client.

**Comment by ygini** [comment]
@simo5 client side is Heimdal built in iOS and macOS…

**Comment by simo5** [comment]
Yeah, I guess you need to open a bug with Apple, they are violating the MS-KKDCP spec.
I do not think we should accept malformed packets, unless they have a good explanation why this is ok to do.

**Comment by tiran** [comment]
I might found the buggy code in Apple's fork of Heimdal. I'm only familiar with MIT Kerberos, so my analysis might be wrong. The `recv_http` function deals with 4 byte prefix, but the `prepare_http` function doesn't add 4 byte prefix to the payload.

https://github.com/apple-oss-distributions/Heimdal/blob/48f86d0ceef220f75b16f0fc8266b53d50129c38/lib/krb5/send_to_kdc.c#L689

It is very unlikely that the bug is in kdcproxy. The project has been around for a decade and has been used in production with MIT Kerberos, Microsoft Active Directory's Kerberos, and FreeIPA / RHEL IdM. It's more likely that an Apple engineer  misread the RFC and missed the fact, that the internal payload has an additional size header. The four bytes caught me by surprise, too.

**Comment by simo5** [comment]
@ygini to be clear, you could easily patch the code to add the prefix 4 bytes instead of checking them as a local modification. It would temporarily make it work for your case (hopefully).

But I would strongly recommend reporting this issue to Apple if they claim MS-KKDCP support because it doesn't look like their implementation is compliant, they may have tested it only internally instead of testing against a proper Microsoft client/server.

**Comment by ygini** [comment]
Here is the answer I've got from Apple Feedback system, referencing our GitHub Issue here.

> The Heimdal encoding is correct.  The three byte length is par to how OCTEX STRINGs are encoded in DER when the length is over 127 bytes.  https://learn.microsoft.com/en-us/windows/win32/seccertenroll/about-octet-string

> In your example, the encoded data is 04 81 AD. 8 means it is over 127 bytes in length and 1 means that the length is stored in one byte.  AD is the DER encoded length (or 173) of the kerb-message.  The value of the kerb-message field is the 4 byte length, 169 (00 00 00 A9), and the data per https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-kkdcp/5778aff5-b182-4b97-a970-29c7f911eef2.

**Comment by tiran** [comment]
Apple support did not understand the problem...

Yes, the three bytes are the correct encoding header for an octet string. **HOWEVER** per [RFC 4120](https://www.rfc-editor.org/rfc/rfc4120.html#section-7.2.2) the payload is not just an ASN.1 octet string. The payload is a 4 bytes header plus an octet string.

**Comment by ygini** [comment]
I will try to make this move…

**Comment by tiran** [comment]
Good luck!

Here is a link to MIT Kerberos implementation for KDC proxy request (added in 2014): https://github.com/krb5/krb5/blob/d6186c447f9ec85b9f5fb11f315db45c7648e919/src/lib/krb5/os/sendto_kdc.c#L615-L625 . Maybe it helps.

**Comment by tiran** [comment]
And we found the bug in Apple's Heimdal. https://github.com/unofficial-opensource-apple/Heimdal/blob/OS_X-10.10/lib/krb5/send_to_kdc.c#L768-L773

```C
static struct host_fun kkdcp_fun = {
    prepare_udp,
    send_kkdcp,
    recv_tcp,
    1
};
```

KKDCP should use the prepare_tcp function, which adds the four bytes header with [krb5_store_data](https://github.com/unofficial-opensource-apple/Heimdal/blob/OS_X-10.10/lib/krb5/store.c#L654)

**Comment by BaaaZen** [comment]
FYI: It seems like Apple has fixed the problem with macOS 15

https://github.com/apple-oss-distributions/Heimdal/compare/Heimdal-689.140.1...Heimdal-693.0.4

**Comment by ygini** [comment]
Indeed I can confirm that Apple has fixed the issue on their side. I did quick test and indeed it seems to works. Sorry that I forgot to close this issue when I got notified on the fix.
